In [18]:
import numpy as np

# Create a 3x3x3 array with random values 

In [19]:
np.random.rand(3,3,3)

array([[[0.58014841, 0.27284043, 0.62789857],
        [0.54054065, 0.43622638, 0.71238986],
        [0.06360405, 0.21375704, 0.35462671]],

       [[0.4812064 , 0.94262112, 0.39139706],
        [0.61467718, 0.16972767, 0.68414803],
        [0.63300981, 0.06011013, 0.59925081]],

       [[0.76771923, 0.69605068, 0.35551922],
        [0.38843621, 0.04705153, 0.94390688],
        [0.44046705, 0.08277779, 0.16241793]]])

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [20]:
p = np.diag(1+np.arange(4), k=-1)
print(p)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Create a 8x8 matrix and fill it with a checkerboard pattern

In [21]:
q = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(q)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Normalize a 5x5 random matrix

In [22]:
arr = np.random.random((5,5))
narr = (arr - np.mean(arr)) / (np.std(arr))
print(narr)

[[ 0.84494563 -0.38079518  1.26730523 -1.01797178  0.61752884]
 [-0.06978504  0.68360633  0.8572562  -1.91698609 -0.07817725]
 [-1.29266936 -0.76188083 -1.7159702   0.60551317 -0.73784469]
 [ 0.72954657  1.17353306  1.07206099  0.88917094 -1.76149267]
 [-0.62587231  0.7027135   1.45337859 -0.38688936 -0.15022427]]


#  How to find common values between two arrays?

In [23]:
a1 = np.random.randint(0,10,50)
a2 = np.random.randint(0,10,50)
print(np.intersect1d(a1,a2))

[1 2 3 4 5 6 7 8 9]


# How to get the dates of yesterday, today and tomorrow?

In [24]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-09-05 2020-09-06 2020-09-07


# Consider two random array A and B, check if they are equal

In [25]:
a1 = np.random.randint(0,5,5)
a2 = np.random.randint(0,5,5)
print(np.array_equal(a1,a2))

False


# Create random vector of size 10 and replace the maximum value by 0 

In [26]:
v = np.random.rand(10)
v[v.argmax()] = 0
print(v)

[0.78871692 0.53167566 0.68319579 0.66413479 0.05429511 0.90629214
 0.         0.25530253 0.02588268 0.18025004]


# How to print all the values of an array?

In [27]:
arr = np.ones((5, 5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Subtract the mean of each row of a matrix

In [28]:
arr = np.random.randn(5, 5)
print("before\n", arr)
arr = arr - np.mean(arr,axis=1)
print("\nafter\n", arr)

before
 [[ 1.35147316 -0.41852647  0.43153402  1.36927245  0.19996561]
 [ 0.07996444 -0.94345631  1.51602109  0.12959748  0.79781265]
 [-2.39388903  0.39977295  0.27035473  1.08496014 -1.12014821]
 [-0.3975661  -0.2936526  -1.76636122  0.83355007  1.74586179]
 [-1.49081529  0.46991439  1.80935492  0.24203637 -0.16565048]]

after
 [[ 0.7647294  -0.73451434  0.7833239   1.34490606  0.02699762]
 [-0.50677931 -1.25944418  1.86781097  0.1052311   0.62484466]
 [-2.98063278  0.08378508  0.62214461  1.06059375 -1.29311619]
 [-0.98430985 -0.60964046 -1.41457134  0.80918368  1.5728938 ]
 [-2.07755904  0.15392652  2.16114481  0.21766998 -0.33861846]]


# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [29]:
arr1= np.random.randint(0,5,10)
print(arr1)
arr2= np.random.randint(0,8,10)
print (arr2)

[3 4 0 2 1 4 1 0 1 4]
[7 0 5 5 4 7 2 7 2 5]


In [30]:
arr1 += np.bincount(arr2, minlength=len(arr1))
print (arr1)

[4 4 2 2 2 7 1 3 1 4]


# How to get the diagonal of a dot product?

In [31]:
x = np.random.randint(0,10,(3,3))
print(x)
y = np.random.randint(0,10,(3,3))
print(y)
print("Diagonal of a dot product")
print (np.diag(np.dot(x,y)))

[[3 3 3]
 [2 2 1]
 [1 6 9]]
[[2 6 4]
 [6 2 2]
 [6 7 5]]
Diagonal of a dot product
[42 23 61]


# How to find the most frequent value in an array?

In [32]:
arr = np.random.randint(0,10,30)
print(arr)
print(np.bincount(arr).argmax())

[8 8 8 6 3 1 4 5 0 0 4 8 8 7 6 3 9 1 7 2 9 6 6 8 1 4 1 0 0 1]
8


# How to get the n largest values of an array

In [33]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

2

# How to create a record array from a regular array?

In [34]:
x = np.array([("Hello", 123, 3),
              ("World", 306, 2)])
rec = np.core.records.fromarrays(x.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

print (rec)

[(b'Hello', 123., 3) (b'World', 306., 2)]
